sudo: false
dist: trusty

language: python

jobs:
  include:
    - python: "2.7"
      script: python -m unittest discover python2
    - python: "3.4"
      script: python -m unittest discover python3
    - python: "3.5"
      script: python -m unittest discover python3
    - python: "3.6"
      script: python -m unittest discover python3
    - stage: deploy
      deploy:
      - provider: pypi
        user: norcuni
        server: https://test.pypi.org/legacy/
        password:
          secure: tSS0BD16HGrBoo3gHT+0ormIQzvs7nkhygNWdiEBPB7bj9QknGBgZzsBnQVI6EpzpgA+F2OjsTrTd8dpYeiC3apVyJ9kj1Wc7MovPCaMscLwemX34b7lLsz3GMwdVX/L1gAutb+1ftoiEJxGwmRhlcLO4r+5D1GRkdgARHU2RRm1GUjlHD1s4ubpmiosVrLpqPgygwgkF5eLet16eLY0wgbqQ0IgP4dqgTCeKRcrzAYLEmbgKSFh7bsGk++yFCrPxgkgL/udfNjiQy7q8tWVzOE7np6rHddk0wX0Tg8vey8CPIMnkLIhdClbPTFBU794uyMoKMtBywoPhPIaRyGB1AzpXDqHZnNZCF8H3JsgPac3qNfw1n3pE3ji+dpJ4hU2DNPw6golOzbvngReDqkXq4JbE0+mLY1gqF77mlbwlGu4pl35ioA4KJz9oahQXgCaOBowSdTClgtFS6Sh//myEiWyn0lJRBkdAHk3KhfoZR+tahEfnU3F2s+ATtT4gDBd/EbpuTWql7wySpJfXF+g8FnvBnNN09lvJrxcCxZGi3wWXlrusNE3ASD/FVYSvLuEJr/XpsOtcm5x4Ay6E7tA4VtmH338c3kBK03RM1r0nLotcsZcZ7pz0M7N5hPFYXWwZsS4myl2BD8XE9Neapm4BKm+X7oi0FVfPzAicRedR8A=
        on:
          branch: master
