sudo: false
dist: trusty

language: python

jobs:
  include:
    - python: "2.7"
      script: python -m unittest discover python2
    - python: "3.4"
      script: python -m unittest discover python3
    - python: "3.5"
    - python: "3.6"
    - stage: deploy
      script: echo run once!
